apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pg-deploy
  name: pg-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pg-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pg-app
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        resources: {}
        envFrom:
        - secretRef:
            name: db-secret
status: {}
