apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-wordpress-vol-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: nginx-wordpress-vol
