Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "debian/bookworm64"
    master.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    master.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
  end
end
