version: '2.4'

services:

  backend:
    restart: always
    hostname: backend
    depends_on:
      weaviate:
        condition: service_started
      t2v-transformers:
        condition: service_started
    networks:
      - fast_api
    ports:
      - ${BACKEND_PORT}:9001
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    environment:
      ENV:             ${BACKEND_ENV}

  frontend:
    restart: always
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    depends_on:
      backend:
        condition: service_started
    networks:
      - fast_api
    ports:
      - ${FRONTEND_PORT}:9005

networks:
  fast_api:
    driver: bridge
    name: fast_api
