version: '2.4'

services:
  backend:
    hostname: backend
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - unvolt_test_net
    ports:
      - ${BACKEND_PORT}:9001
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    environment:
      ENV:             ${BACKEND_ENV}

  fronend:
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: test
    depends_on:
      backend:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - unvolt_test_net
    ports:
      - ${FRONTEND_PORT}:9005

  postgres:
    hostname: postgres
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - unvolt_test_net
    environment:
      POSTGRES_PASSWORD:    ${POSTGRES_PASSWORD}
      POSTGRES_USER:        ${POSTGRES_USER}
      POSTGRES_DB:          ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 3s

networks:
  unvolt_test_net:
    driver: bridge
    name: unvolt_test_net
