#!/bin/sh

set -e

# empty message of the day.
echo -n > /etc/motd

# remove some unused packages
DEBIAN_FRONTEND=noninteractive apt-get purge -y laptop-detect tasksel emacsen-common ienglish-common ispell

# install some additional packages
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends linux-headers-amd64 openssh-server sudo time openssl gnutls-bin zip unzip bzip2 lynx vim vim-scripts curl whois screen git gpg-agent gnupg software-properties-common tcpdump make zsh ufw

# members of `sudo` group are not asked for password.
sed -i 's/^%sudo\tALL=(ALL:ALL) ALL/%sudo\tALL=(ALL:ALL) NOPASSWD:ALL/' /etc/sudoers

# new users should be put into the "users" group
sed -i 's/^USERGROUPS=yes/USERGROUPS=no/' /etc/adduser.conf

# fix the time server configuration
sed -i 's/^#NTP=/NTP=us.pool.ntp.org/' /etc/systemd/timesyncd.conf

# unpack the postinstall tar file
tar -z -x -C /tmp -f /tmp/postinstall.tar.gz

# install global things and root things
mkdir -m700 -p /root/.ssh
cp /tmp/postinstall.d/resolv.conf /etc/resolv.conf
cp /tmp/postinstall.d/apt.conf.d/50unattended-upgrades /etc/apt/apt.conf.d/50unattended-upgrades
cp /tmp/postinstall.d/apt.conf.d/20auto-upgrades /etc/apt/apt.conf.d/20auto-upgrades
cp /tmp/postinstall.d/vimrc /root/.vimrc
cp /tmp/postinstall.d/bash_login /root/.bash_login

# add our sudoers file for debian
cp /tmp/postinstall.d/sudoers /etc/sudoers.d/debian
chmod 400 /etc/sudoers.d/debian

# install ssh keys and other things for debian user
mkdir -m700 -p /home/debian/.ssh
cp /tmp/postinstall.d/authorized_keys /home/debian/.ssh/authorized_keys
cp /tmp/postinstall.d/vimrc /home/debian/.vimrc
cp /tmp/postinstall.d/bash_login /home/debian/.bash_login

# fix permissions on root home directory
chmod 700 /root
chmod 600 /root/.bash_login

# fix permissions on debian home directory
chown -R debian:debian /home/debian
chmod 700 /home/debian
chmod 600 /home/debian/.bash_login /home/debian/.ssh/authorized_keys

rm -rf /etc/ssh/sshd_config
mv /tmp/postinstall.d/sshd_config /etc/ssh/sshd_config
