apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-var-www-vol-letsencrypt-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      pv: nginx-var-www-letsencrypt-vol
