Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "debian/bookworm64"
    master.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    master.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
  end

  config.vm.define "worker1" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    worker.vm.provider "virtualbox" do |v|
      v.cpus = 1 
      v.memory = 1024
    end
  end

  config.vm.define "worker2" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    worker.vm.provider "virtualbox" do |v|
      v.cpus = 1 
      v.memory = 1024
    end
  end

  config.vm.define "jumpbox" do |jumpbox|
    jumpbox.vm.box = "debian/bookworm64"
    jumpbox.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    jumpbox.vm.provider "virtualbox" do |v|
      v.cpus = 1 
      v.memory = 512
    end
  end

end
