apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc
  namespace: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
