apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pg-service
  name: pg-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5432
  selector:
    app: pg-deploy
status:
  loadBalancer: {}
